-- Generated by HyprMon. Manual changes may be overwritten.

-- hl.monitor({ output = "eDP-1", mode = "2880x1920@120.00", position = "0x0", scale = 1.50 })
-- hl.monitor({ output = "DP-3", mode = "3840x2160@60.00", position = "1920x-544", scale = 1.50, transform = 1 })
